"""Layer 2 — dynamic 'what this chart is actually saying' takeaways.

Generated by local Ollama from a small structured summary of the chart's
numerics (NOT the raw data — keep prompts cheap). Cached in
data/cache/descriptions.json keyed by (chart_id, data_hash).

Hard rules from spec §10:
- Never call cloud LLMs. Ollama only.
- Never write LLM output to papier.db.
- Strict JSON-out contract. Single retry on malformed output.
- Fallback to a quiet 'AI takeaway unavailable' line — never raise into the UI.
"""
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any

DEFAULT_MODEL = os.environ.get("SIGNAL_TERMINAL_OLLAMA_MODEL", "llama3.1:8b-instruct-q4_K_M")
DEFAULT_CACHE = Path("data/cache/descriptions.json")
UNAVAILABLE = "AI takeaway unavailable — start Ollama locally to generate."

_PROMPT_TEMPLATE = (
    "You are an analyst writing a one-paragraph takeaway for a chart in a "
    "read-only sentiment dashboard. Read the JSON summary of the chart and "
    "write 2-4 sentences in plain English that name the SPECIFIC patterns "
    "visible in the numbers — do not restate definitions, do not hedge with "
    "'this could mean.' Be concrete. Avoid hype.\n\n"
    "Chart id: {chart_id}\n"
    "Numbers (JSON):\n{summary}\n\n"
    "Reply with strict JSON only, no prose outside the JSON:\n"
    '{{"takeaway": "<your 2-4 sentence takeaway>"}}\n'
)


# --------------------------------------------------------------------------- #
# hashing + cache
# --------------------------------------------------------------------------- #
def _hash_summary(summary: dict[str, Any]) -> str:
    """Stable short hash of the summary dict — the cache key tail."""
    blob = json.dumps(summary, sort_keys=True, default=str).encode("utf-8")
    return hashlib.sha256(blob).hexdigest()[:16]


def _load_cache(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return {}


def _save_cache(path: Path, cache: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(cache, indent=2, sort_keys=True))
    tmp.replace(path)


# --------------------------------------------------------------------------- #
# Ollama call (with single retry on bad JSON)
# --------------------------------------------------------------------------- #
def _call_ollama(prompt: str, *, model: str) -> str | None:
    """Returns the parsed takeaway string, or None on failure.

    Ollama may not be installed; the call may time out; the model may return
    malformed JSON. Any of those collapse to None.
    """
    try:
        import ollama
    except ImportError:
        return None

    for attempt in range(2):
        try:
            resp = ollama.chat(
                model=model,
                format="json",
                options={"temperature": 0.2},
                messages=[
                    {"role": "system",
                     "content": "You output only valid JSON. No prose outside the JSON."},
                    {"role": "user", "content": prompt},
                ],
            )
            raw = resp["message"]["content"] if isinstance(resp, dict) else resp.message.content
            obj = json.loads(raw)
            takeaway = obj.get("takeaway")
            if isinstance(takeaway, str) and takeaway.strip():
                return takeaway.strip()
        except (json.JSONDecodeError, KeyError, AttributeError, Exception):  # noqa: BLE001
            if attempt == 0:
                continue
            return None
    return None


# --------------------------------------------------------------------------- #
# public API
# --------------------------------------------------------------------------- #
def interpret(
    chart_id: str,
    summary: dict[str, Any],
    *,
    enabled: bool = True,
    model: str | None = None,
    cache_path: Path | None = None,
) -> str:
    """Return a 2-4 sentence dynamic takeaway for (chart_id, summary).

    Cached aggressively keyed by (chart_id, hash(summary)). When `enabled` is
    False, returns "" — the view layer can skip rendering the takeaway block
    entirely.
    """
    if not enabled:
        return ""

    cache_path = cache_path or DEFAULT_CACHE
    model = model or DEFAULT_MODEL
    key = f"{chart_id}:{_hash_summary(summary)}"

    cache = _load_cache(cache_path)
    if key in cache:
        return cache[key]

    prompt = _PROMPT_TEMPLATE.format(chart_id=chart_id, summary=json.dumps(summary, default=str))
    text = _call_ollama(prompt, model=model)
    if text is None:
        return UNAVAILABLE

    cache[key] = text
    _save_cache(cache_path, cache)
    return text
